In [1]:
import numpy as np

# all()

In [2]:
a = np.array([
    [1, 1, 1],
    [1, 0, 1],
    [1, 0, 1]
])
a

array([[1, 1, 1],
       [1, 0, 1],
       [1, 0, 1]])

In [3]:
np.all(a)

False

In [16]:
a.all()

False

In [6]:
b = np.ones((3, 3))
b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [7]:
np.all(b)

True

In [17]:
b.all()

True

In [8]:
np.all(a < 2)

True

In [23]:
(a < 2).all()

True

In [9]:
np.all( b % 3 < 2)

True

In [12]:
c = np.array([
    [1, 1, 1],
    [1, 0, 1]
])
c

array([[1, 1, 1],
       [1, 0, 1]])

Check elements element-wisely by row

row axis will be contracted

In [13]:
np.all(c, axis=0)

array([ True, False,  True])

In [18]:
c.all(axis=0)

array([ True, False,  True])

Check elements element-wisely by column

column axis will be contracted

In [14]:
np.all(c, axis=1)

array([ True, False])

In [20]:
c.all(axis=1)

array([ True, False])

Keep dimension

In [15]:
np.all(c, axis=0, keepdims=True)

array([[ True, False,  True]])

In [22]:
c.all(axis=0, keepdims=True)

array([[ True, False,  True]])

In [21]:
c.all(keepdims=True)

array([[False]])

# any()

In [26]:
a = np.random.randint(10, size=(2, 3))
a

array([[9, 9, 2],
       [7, 9, 3]])

In [27]:
np.any(a == 9)

True

In [28]:
(a == 9).any()

True

In [29]:
np.any(a == 5)

False

In [30]:
(a == 5).any()

False

In [31]:
np.any(a % 3 == 0, axis=0)

array([ True,  True,  True])

In [38]:
np.any(a % 3 == 0, axis=0, keepdims=True)

array([[ True,  True,  True]])

In [32]:
(a % 3 == 0).any(axis=0)

array([ True,  True,  True])

In [35]:
np.any(a % 2 == 0, axis=1)

array([ True, False])

In [37]:
np.any(a % 2 == 0, axis=1, keepdims=True)

array([[ True],
       [False]])

In [36]:
(a % 2 == 0).any(axis=1)

array([ True, False])

In [39]:
np.any(a > 2, keepdims=True)

array([[ True]])

# Compare two arrays

In [40]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [45]:
b = np.array([
    [7, 8, 9],
    [5, 5, 5]
])
b

array([[7, 8, 9],
       [5, 5, 5]])

In [46]:
(a == b).any(axis=0)

array([False,  True, False])

In [47]:
(a == b).any(axis=1)

array([False,  True])