In [1]:
import numpy as np
from pprint import pprint

In [2]:
b = np.arange(12).reshape(3, 4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

The input array must have identical dimensions as appended array

In [3]:
input_array = [[12, 13, 14, 15]]
np.append(b, input_array, axis=0)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [5]:
input_array = [12, 13, 14, 15]
try:
    np.append(b, input_array, axis=0)
except ValueError as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)


Append by different axis

In [6]:
c = np.arange(12).reshape(3, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [7]:
d = np.linspace(0, 26, 12).reshape(3, 4)
d

array([[ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [8]:
# d is being appended to c by row
np.append(c, d, axis=0)

array([[ 0.        ,  1.        ,  2.        ,  3.        ],
       [ 4.        ,  5.        ,  6.        ,  7.        ],
       [ 8.        ,  9.        , 10.        , 11.        ],
       [ 0.        ,  2.36363636,  4.72727273,  7.09090909],
       [ 9.45454545, 11.81818182, 14.18181818, 16.54545455],
       [18.90909091, 21.27272727, 23.63636364, 26.        ]])

In [9]:
# d is being appended to c by column
np.append(c, d, axis=1)

array([[ 0.        ,  1.        ,  2.        ,  3.        ,  0.        ,
         2.36363636,  4.72727273,  7.09090909],
       [ 4.        ,  5.        ,  6.        ,  7.        ,  9.45454545,
        11.81818182, 14.18181818, 16.54545455],
       [ 8.        ,  9.        , 10.        , 11.        , 18.90909091,
        21.27272727, 23.63636364, 26.        ]])