In [2]:
import numpy as np

# np.zeros()

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.zeros_like()

use np.zeros_like() if needed shape is same as another existing array

In [5]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.zeros(a.shape) == np.zeros_like(a)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# np.ones()

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones(4, dtype=np.int8)

array([1, 1, 1, 1], dtype=int8)

# np.ones_like()

In [11]:
a = np.array([[1,2,3], [2,3,4]])

In [12]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
b = np.array([2,3,4], dtype='int8')

In [14]:
np.ones_like(b)

array([1, 1, 1], dtype=int8)

# np.empty()

In [15]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### time comparison among each generator

In [17]:
%timeit np.zeros(10000)

2.47 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
%timeit np.ones(10000)

3.99 µs ± 252 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
%timeit np.empty(10000)

1.01 µs ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# np.arange(start, stop, step, dtype=None)

specify parameters start, stop

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(-10)

array([], dtype=int64)

In [5]:
np.arange(4.5)

array([0., 1., 2., 3., 4.])

In [6]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# start from 0.5 and default step = 1
np.arange(0.5, 5.5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [9]:
np.arange(0.55, 5.55)

array([0.55, 1.55, 2.55, 3.55, 4.55])

specify parameter step

In [10]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [11]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

In [12]:
np.arange(5, 2, -1)

array([5, 4, 3])

In [13]:
np.arange(stop=3, step=1)  # default start = 0

array([0, 1, 2])

set dtype

In [14]:
np.arange(5, dtype='float64')

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(5.0, dtype='int')

array([0, 1, 2, 3, 4])

In [16]:
np.arange(0, 5, 0.5, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
np.arange(0, 5, 1.5, dtype='int')

array([0, 1, 2, 3])

# np.linspace(start, stop, num, endpoint, retstep, dtype)

start from 0 and stop at 1, and default num is 50

In [19]:
np.linspace(0, 1)

array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
       0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
       0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
       0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
       0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
       0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
       0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
       0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
       0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
       0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ])

In [20]:
np.linspace(0, 49)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35., 36., 37., 38.,
       39., 40., 41., 42., 43., 44., 45., 46., 47., 48., 49.])

In [21]:
np.linspace(0, 2, 3)

array([0., 1., 2.])

In [23]:
np.linspace(0, 2, num=3)

array([0., 1., 2.])

In [22]:
np.linspace(0, -2, 3)

array([ 0., -1., -2.])

set endpoint

In [24]:
np.linspace(0, 2, num=3, endpoint=False)

array([0.        , 0.66666667, 1.33333333])

In [25]:
np.linspace(0, 2, num=3, endpoint=True)

array([0., 1., 2.])

set retstep

In [26]:
np.linspace(0, 1, retstep=True)

(array([0.        , 0.02040816, 0.04081633, 0.06122449, 0.08163265,
        0.10204082, 0.12244898, 0.14285714, 0.16326531, 0.18367347,
        0.20408163, 0.2244898 , 0.24489796, 0.26530612, 0.28571429,
        0.30612245, 0.32653061, 0.34693878, 0.36734694, 0.3877551 ,
        0.40816327, 0.42857143, 0.44897959, 0.46938776, 0.48979592,
        0.51020408, 0.53061224, 0.55102041, 0.57142857, 0.59183673,
        0.6122449 , 0.63265306, 0.65306122, 0.67346939, 0.69387755,
        0.71428571, 0.73469388, 0.75510204, 0.7755102 , 0.79591837,
        0.81632653, 0.83673469, 0.85714286, 0.87755102, 0.89795918,
        0.91836735, 0.93877551, 0.95918367, 0.97959184, 1.        ]),
 0.02040816326530612)

In [27]:
np.linspace(0, 2, num=3, retstep=True)

(array([0., 1., 2.]), 1.0)

In [28]:
np.linspace(0, 2, num=3, retstep=False)

array([0., 1., 2.])

# identity matrix: np.eye() and np.identity()

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [31]:
np.eye(2, 3)

array([[1., 0., 0.],
       [0., 1., 0.]])

In [32]:
np.eye(5, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

using k to shift the diagonal line

In [33]:
np.eye(5, k=0)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [34]:
np.eye(5, k=1)

array([[0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [36]:
np.eye(5, k=-1)

array([[0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.]])

In [37]:
np.eye(5, k=3)

array([[0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

identity() creates squared matrix only

In [38]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [39]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [41]:
%timeit np.eye(10_000)

26.8 ms ± 2.24 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
%timeit np.identity(10_000)

24.3 ms ± 254 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
