In [1]:
import numpy as np

# np.hstack()

horizontal stack, so stack elements along with axis = 1 direction

### 1-D array

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = np.arange(2)
b

array([0, 1])

In [4]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

### 2-D array

In [5]:
c = np.arange(4).reshape(2, 2)
c

array([[0, 1],
       [2, 3]])

try to combine 1-D array and 2-D array

In [6]:
try:
    np.hstack((a, c))
except ValueError as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)


In [7]:
d = np.arange(6).reshape(2, 3)
d

array([[0, 1, 2],
       [3, 4, 5]])

combine 2-D arrays

In [8]:
np.hstack((c, d))

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

combine 3-D arrays

In [9]:
e = np.arange(12).reshape(2, 2, 3)
e

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
f = np.arange(6).reshape(2, 1, 3)
f

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [11]:
np.hstack((e, f))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

# np.vstack()

### combine 2-D arrays

In [12]:
a = np.arange(12).reshape(-1, 1)
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [13]:
b = np.arange(2).reshape(-1, 1)
b

array([[0],
       [1]])

In [14]:
np.vstack((a, b))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [15]:
c = np.arange(2).reshape(1, 2)
c

array([[0, 1]])

In [17]:
try:
    np.vstack((a, c))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2


In [18]:
d = np.arange(4).reshape(2, 2)
d

array([[0, 1],
       [2, 3]])

In [19]:
np.vstack((c, d))

array([[0, 1],
       [0, 1],
       [2, 3]])

### combine 3-D arrays

In [20]:
e = np.arange(24).reshape(4, 3, 2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [21]:
f = np.arange(6).reshape(1, 3, 2)
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [22]:
g = np.vstack((e, f))
g

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

In [23]:
g.shape

(5, 3, 2)