In [2]:
import numpy as np

# np.zeros()

In [2]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [3]:
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [4]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# np.zeros_like()

use np.zeros_like() if needed shape is same as another existing array

In [5]:
a = np.arange(12).reshape(3,-1)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [6]:
np.zeros(a.shape) == np.zeros_like(a)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [7]:
b = np.zeros_like(a)
b

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

# np.ones()

In [8]:
np.ones(3)

array([1., 1., 1.])

In [9]:
np.ones((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
np.ones(4, dtype=np.int8)

array([1, 1, 1, 1], dtype=int8)

# np.ones_like()

In [11]:
a = np.array([[1,2,3], [2,3,4]])

In [12]:
np.ones_like(a)

array([[1, 1, 1],
       [1, 1, 1]])

In [13]:
b = np.array([2,3,4], dtype='int8')

In [14]:
np.ones_like(b)

array([1, 1, 1], dtype=int8)

# np.empty()

In [15]:
np.empty(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.empty((2, 3))

array([[1., 1., 1.],
       [1., 1., 1.]])

### time comparison among each generator

In [17]:
%timeit np.zeros(10000)

2.47 µs ± 25.7 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [18]:
%timeit np.ones(10000)

3.99 µs ± 252 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [19]:
%timeit np.empty(10000)

1.01 µs ± 10.8 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# np.arange(start, stop, step, dtype=None)

specify parameters start, stop

In [3]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [4]:
np.arange(-10)

array([], dtype=int64)

In [5]:
np.arange(4.5)

array([0., 1., 2., 3., 4.])

In [6]:
np.arange(1, 8)

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
np.arange(2, 10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
# start from 0.5 and default step = 1
np.arange(0.5, 5.5)

array([0.5, 1.5, 2.5, 3.5, 4.5])

In [9]:
np.arange(0.55, 5.55)

array([0.55, 1.55, 2.55, 3.55, 4.55])

specify parameter step

In [10]:
np.arange(2, 12, 2)

array([ 2,  4,  6,  8, 10])

In [11]:
np.arange(2, 5, 0.2)

array([2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4, 3.6, 3.8, 4. , 4.2, 4.4,
       4.6, 4.8])

In [12]:
np.arange(5, 2, -1)

array([5, 4, 3])

In [13]:
np.arange(stop=3, step=1)  # default start = 0

array([0, 1, 2])

set dtype

In [14]:
np.arange(5, dtype='float64')

array([0., 1., 2., 3., 4.])

In [15]:
np.arange(5.0, dtype='int')

array([0, 1, 2, 3, 4])

In [16]:
np.arange(0, 5, 0.5, dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [17]:
np.arange(0, 5, 0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5])

In [18]:
np.arange(0, 5, 1.5, dtype='int')

array([0, 1, 2, 3])