In [47]:
import numpy as np
import timeit

# np.hstack()

horizontal stack, so stack elements along with axis = 1 direction

### 1-D array

In [2]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [3]:
b = np.arange(2)
b

array([0, 1])

In [4]:
np.hstack((a, b))

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11,  0,  1])

### 2-D array

In [5]:
c = np.arange(4).reshape(2, 2)
c

array([[0, 1],
       [2, 3]])

try to combine 1-D array and 2-D array

In [6]:
try:
    np.hstack((a, c))
except ValueError as e:
    print(e)

all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)


In [7]:
d = np.arange(6).reshape(2, 3)
d

array([[0, 1, 2],
       [3, 4, 5]])

combine 2-D arrays

In [8]:
np.hstack((c, d))

array([[0, 1, 0, 1, 2],
       [2, 3, 3, 4, 5]])

combine 3-D arrays

In [9]:
e = np.arange(12).reshape(2, 2, 3)
e

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [10]:
f = np.arange(6).reshape(2, 1, 3)
f

array([[[0, 1, 2]],

       [[3, 4, 5]]])

In [11]:
np.hstack((e, f))

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 0,  1,  2]],

       [[ 6,  7,  8],
        [ 9, 10, 11],
        [ 3,  4,  5]]])

# np.vstack()

### combine 2-D arrays

In [12]:
a = np.arange(12).reshape(-1, 1)
a

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [13]:
b = np.arange(2).reshape(-1, 1)
b

array([[0],
       [1]])

In [14]:
np.vstack((a, b))

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [ 0],
       [ 1]])

In [15]:
c = np.arange(2).reshape(1, 2)
c

array([[0, 1]])

In [17]:
try:
    np.vstack((a, c))
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 1 and the array at index 1 has size 2


In [18]:
d = np.arange(4).reshape(2, 2)
d

array([[0, 1],
       [2, 3]])

In [19]:
np.vstack((c, d))

array([[0, 1],
       [0, 1],
       [2, 3]])

### combine 3-D arrays

In [20]:
e = np.arange(24).reshape(4, 3, 2)
e

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

In [21]:
f = np.arange(6).reshape(1, 3, 2)
f

array([[[0, 1],
        [2, 3],
        [4, 5]]])

In [22]:
g = np.vstack((e, f))
g

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]],

       [[ 0,  1],
        [ 2,  3],
        [ 4,  5]]])

In [23]:
g.shape

(5, 3, 2)

# np.r_  (not np.r_())

default mode

In [2]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.r_[a, b]

array([1, 2, 3, 4, 5, 6])

In [4]:
np.r_[100, 101, 102, np.array([2, 3]), 99.9]

array([100. , 101. , 102. ,   2. ,   3. ,  99.9])

In [5]:
c = np.zeros((2, 3))
d = np.ones((3, 3))
np.r_[c, d]

array([[0., 0., 0.],
       [0., 0., 0.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [6]:
d = np.ones((3 ,4))
try:
    np.r_[c, d]
except ValueError as e:
    print(e)

all the input array dimensions except for the concatenation axis must match exactly, but along dimension 1, the array at index 0 has size 3 and the array at index 1 has size 4


### set x, y, z in np.r_['x, y, z', array/number, array/number, ...]

x: which axis to combine arrays. default value = 0

y: how many axes/dimensions will be after the operation.

z: which axis will original main axis shift to. default value = -1

In [7]:
a = np.ones((2, 2))
b = np.zeros((2, 2))
np.r_['1', a, b]

array([[1., 1., 0., 0.],
       [1., 1., 0., 0.]])

In [8]:
np.r_['1', a, b].shape

(2, 4)

In [9]:
np.r_['0', a, b]

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.r_['0', a, b].shape

(4, 2)

In [11]:
np.r_[a, b]

array([[1., 1.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

In [12]:
np.r_[a, b].shape

(4, 2)

In [13]:
shape = (2, 2, 2)
c = np.ones(shape)
d = np.zeros(shape)
c

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [14]:
d

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [15]:
np.r_['0', c, d]

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

In [16]:
np.r_['0', c, d].shape

(4, 2, 2)

In [17]:
np.r_['1', c, d]

array([[[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]],

       [[1., 1.],
        [1., 1.],
        [0., 0.],
        [0., 0.]]])

In [18]:
np.r_['1', c, d].shape

(2, 4, 2)

In [19]:
np.r_['2', c, d]

array([[[1., 1., 0., 0.],
        [1., 1., 0., 0.]],

       [[1., 1., 0., 0.],
        [1., 1., 0., 0.]]])

In [20]:
np.r_['2', c, d].shape

(2, 2, 4)

In [26]:
a = np.arange(3)
b = np.tile([3], 3)

set y value

In [31]:
y = np.r_['0, 2', a, b]
y

array([[0, 1, 2],
       [3, 3, 3]])

In [32]:
y.shape

(2, 3)

In [29]:
y = np.r_['0, 3', a, b]
y

array([[[0, 1, 2]],

       [[3, 3, 3]]])

In [30]:
y.shape

(2, 1, 3)

set z value

In [33]:
z = np.r_['0, 2, -1', a, b]
z

array([[0, 1, 2],
       [3, 3, 3]])

In [34]:
z.shape

(2, 3)

In [35]:
z = np.r_['0, 2, 0', a ,b]
z

array([[0],
       [1],
       [2],
       [3],
       [3],
       [3]])

In [36]:
z.shape

(6, 1)

In [37]:
z = np.r_['0, 3, 0', a, b]
z

array([[[0]],

       [[1]],

       [[2]],

       [[3]],

       [[3]],

       [[3]]])

In [38]:
z.shape

(6, 1, 1)

### generating new array using slicing syntax
#### np.r_ vs. np.arange()

np.r_[start:stop:step, 1-D array1, 1-D array2, ...]

In [39]:
np.r_[0: 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [40]:
np.r_[: 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
np.r_[0: 10: 2]

array([0, 2, 4, 6, 8])

In [42]:
np.r_[10:0:-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

In [45]:
np.r_[0:5, 100, 200, np.array([3, 3])]

array([  0,   1,   2,   3,   4, 100, 200,   3,   3])

In [46]:
%timeit np.r_[0:1_000_000]
%timeit np.arange(1_000_000)

2.58 ms ± 97.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
1.54 ms ± 34.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [48]:
LENGTH = 1_000_000
N = 10_000
result = timeit.timeit("np.arange(LENGTH)", globals=globals(), number=N)
print(f'np.arange(): {result} seconds')
result = timeit.timeit("np.r_[:LENGTH]", globals=globals(), number=N)
print(f'np.r_: {result} seconds')

np.arange(): 15.544830401893705 seconds
np.r_: 24.525806366000324 seconds


### create matrix

np.r_['r/c', array/number, array/number, ...]

r: row

c: column

In [50]:
a = np.array([1, 3, 5])
b = np.array([2, 4, 6])

In [51]:
np.r_['r', a, b]

matrix([[1, 3, 5, 2, 4, 6]])

In [52]:
np.r_['c', a, b]

matrix([[1],
        [3],
        [5],
        [2],
        [4],
        [6]])

In [53]:
c = np.ones((4, 5))
d = np.zeros((2, 5))

In [54]:
np.r_['r', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [55]:
np.r_['c', c, d]

matrix([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [56]:
np.r_['r', c, d].shape == np.r_['c', c, d].shape

True

### np.c_  (not np.c_())

no need to use np.c_ to do other manipulation except for combining last axis

use np.r_ instead

In [57]:
a = np.ones((3, 2))
b = np.zeros((3, 3))
a

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [58]:
b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [59]:
np.c_[a, b]

array([[1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.],
       [1., 1., 0., 0., 0.]])

In [60]:
c = np.zeros(3)
c

array([0., 0., 0.])

In [61]:
np.c_[a, c]

array([[1., 1., 0.],
       [1., 1., 0.],
       [1., 1., 0.]])

In [62]:
np.c_[a, c].shape

(3, 3)