In [1]:
import numpy as np

# .flatten()

In [2]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [3]:
b = a.flatten()
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [4]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
print(a.shape)
print(b.shape)

(2, 5)
(10,)


In [6]:
c = np.arange(12).reshape(2, 2, 3)
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [7]:
d = c.flatten()
c

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

In [8]:
d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
print(c.shape)
print(d.shape)

(2, 2, 3)
(12,)


# np.ravel()

In [10]:
a = np.arange(10).reshape(2, 5)
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [11]:
a.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.ravel(a)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
a

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [14]:
a.ravel(order='C')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
a.ravel(order='F')

array([0, 5, 1, 6, 2, 7, 3, 8, 4, 9])

In [16]:
b = np.arange(10).reshape(2, 5, order='F')
b

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [17]:
b.ravel(order='F')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [18]:
# order = A means output as the same order as input order, so if storing order is F, then output in the way of F
b.ravel(order='A')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
b.ravel()

array([0, 2, 4, 6, 8, 1, 3, 5, 7, 9])

In [20]:
c = np.arange(10).reshape(2, 5, order='C')
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [21]:
# output as the same order as input order C
c.ravel(order='A')

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])