In [1]:
import numpy as np

In [2]:
a = np.array([0, 1, 2])
b = np.array([4, 0])

In [3]:
np.meshgrid(a, b)

[array([[0, 1, 2],
        [0, 1, 2]]),
 array([[4, 4, 4],
        [0, 0, 0]])]

In [4]:
aa, bb = np.meshgrid(a, b)

In [5]:
aa

array([[0, 1, 2],
       [0, 1, 2]])

In [6]:
bb

array([[4, 4, 4],
       [0, 0, 0]])

indexing

In [7]:
aa2, bb2 = np.meshgrid(a, b, indexing='xy')

In [8]:
aa2

array([[0, 1, 2],
       [0, 1, 2]])

In [9]:
bb2

array([[4, 4, 4],
       [0, 0, 0]])

In [10]:
aa3, bb3 = np.meshgrid(a, b, indexing='ij')

In [11]:
aa3

array([[0, 0],
       [1, 1],
       [2, 2]])

In [12]:
bb3

array([[4, 0],
       [4, 0],
       [4, 0]])

sparse

In [13]:
av, bv = np.meshgrid(a, b, sparse=True)

In [14]:
av

array([[0, 1, 2]])

In [15]:
bv

array([[4],
       [0]])