In [2]:
import time
import numpy as np

# amax()

In [4]:
np.amax(np.array([1, 2, 3, 2, 1]))

3

In [5]:
arr = np.arange(1, 5).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [6]:
np.amax(arr, axis=0)

array([3, 4])

find max value along with the direction of axis 0

In [7]:
np.amax(arr, axis=0)

array([3, 4])

find max value along with the direction of axis 1

In [8]:
np.amax(arr, axis=1)

array([2, 4])

keep original dimension 

In [9]:
np.amax(arr, keepdims=True)

array([[4]])

In [10]:
arr_3d = np.arange(12).reshape(2, 3, 2)
np.amax(arr_3d, keepdims=True)

array([[[11]]])

# .max()

In [11]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[ 8, 12, 25, 11, 12],
        [17,  2, 28, 28, 13],
        [ 7, 11, 27, 15,  3]],

       [[ 9,  8,  9, 22,  7],
        [ 8, 27,  4, 12, 11],
        [25,  5, 19, 15,  9]]])

According axis being specified 0, two corresponding 2-D matrice will be compared with each other and select higher value of each element pair

In [12]:
b.max(axis=0)

array([[ 9, 12, 25, 22, 12],
       [17, 27, 28, 28, 13],
       [25, 11, 27, 15,  9]])

According axis being specified 1, compare elements along with row direction inside each matrix and select the highest value of each column of each matrix

In [13]:
b.max(axis=1)

array([[17, 12, 28, 28, 13],
       [25, 27, 19, 22, 11]])

According axis being specified 2, compare elements along with column direction inside each matrix and select the highest value of each row of each matrix

In [14]:
b.max(axis=2)

array([[25, 28, 27],
       [22, 27, 25]])