In [2]:
import time
import numpy as np

# amax()

In [4]:
np.amax(np.array([1, 2, 3, 2, 1]))

3

In [5]:
arr = np.arange(1, 5).reshape(2, 2)
arr

array([[1, 2],
       [3, 4]])

In [6]:
np.amax(arr, axis=0)

array([3, 4])

find max value along with the direction of axis 0

In [7]:
np.amax(arr, axis=0)

array([3, 4])

find max value along with the direction of axis 1

In [8]:
np.amax(arr, axis=1)

array([2, 4])

keep original dimension 

In [9]:
np.amax(arr, keepdims=True)

array([[4]])

In [10]:
arr_3d = np.arange(12).reshape(2, 3, 2)
np.amax(arr_3d, keepdims=True)

array([[[11]]])

# .max()

In [11]:
b = np.random.randint(30, size=(2, 3, 5))
b

array([[[ 8, 12, 25, 11, 12],
        [17,  2, 28, 28, 13],
        [ 7, 11, 27, 15,  3]],

       [[ 9,  8,  9, 22,  7],
        [ 8, 27,  4, 12, 11],
        [25,  5, 19, 15,  9]]])

According axis being specified 0, two corresponding 2-D matrice will be compared with each other and select higher value of each element pair

In [12]:
b.max(axis=0)

array([[ 9, 12, 25, 22, 12],
       [17, 27, 28, 28, 13],
       [25, 11, 27, 15,  9]])

According axis being specified 1, compare elements along with row direction inside each matrix and select the highest value of each column of each matrix

In [13]:
b.max(axis=1)

array([[17, 12, 28, 28, 13],
       [25, 27, 19, 22, 11]])

According axis being specified 2, compare elements along with column direction inside each matrix and select the highest value of each row of each matrix

In [14]:
b.max(axis=2)

array([[25, 28, 27],
       [22, 27, 25]])

# argmax()

In [15]:
a = np.random.randint(10, size=10)
a

array([6, 0, 0, 0, 9, 1, 0, 4, 3, 1])

Return the index of max value

In [16]:
np.argmax(a)

4

Return the first index if multiple elements have identical value

In [17]:
a = np.array([1,2,3,4,5,6,7,6,5,4,7,2,1])
a

array([1, 2, 3, 4, 5, 6, 7, 6, 5, 4, 7, 2, 1])

In [18]:
np.argmax(a)

6

In [19]:
a.argmax()

6

higher dimensional array will be flattened to 1-D array, then find the index of max in the flattened 1-D array

In [20]:
b = np.random.randint(10, size=(3, 4))
b

array([[5, 8, 4, 6],
       [9, 8, 0, 9],
       [6, 8, 3, 7]])

In [21]:
b.argmax()

4

Along with the direction of axis 0 (i.e. row), find the highest value among elements and select the relative location of the target element among elements

In [22]:
b.argmax(axis=0)

array([1, 0, 0, 1])

Along with the direction of axis 1 (i.e. column), find the highest value among elements and select the relative location of the target element among elements

In [23]:
b.argmax(axis=1)

array([1, 0, 1])

### argmax() on 3-D array

In [24]:
c = np.random.randint(10, size=(2, 3, 4))
c

array([[[2, 5, 0, 5],
        [3, 1, 2, 3],
        [3, 3, 9, 9]],

       [[4, 6, 0, 0],
        [4, 5, 1, 1],
        [0, 2, 1, 7]]])

Based on the two matrice on the most outer layer, compare corresponding elements on each matrix and select the location of higher value. 

In [25]:
c.argmax(axis=0)

array([[1, 1, 0, 0],
       [1, 1, 0, 0],
       [0, 0, 0, 0]])

Based on the two matrice on the middle layer, compare corresponding elements on each matrix and select the location of higher value. 

In [26]:
c.argmax(axis=1)

array([[1, 0, 2, 2],
       [0, 0, 1, 2]])

Based on the two matrice on the most inner layer, compare corresponding elements on each matrix and select the location of higher value. 

In [27]:
c.argmax(axis=2)

array([[1, 0, 2],
       [1, 1, 3]])

# argmin()

In [32]:
d = np.random.randn(12).reshape(3, 4)
d = np.abs(d * 10)
d

array([[14.77193331,  0.67770159, 10.9642895 ,  9.7715369 ],
       [ 9.06064085,  8.88315589,  0.41212604,  3.84011112],
       [13.62578938,  8.932695  ,  9.62967216, 27.1576717 ]])

In [33]:
np.argmin(d)

6

In [34]:
np.argmin(d, axis=0)

array([1, 0, 1, 1])

In [35]:
np.argmin(d, axis=1)

array([1, 2, 1])