In [1]:
import numpy as np

# np.newaxis (not np.newaxis())

add new axis, and the number of elements of new dimension is 1

In [2]:
np.newaxis is None

True

In [3]:
x = np.arange(15).reshape(3, 5)
x

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
x1 = x[np.newaxis, :, :]
x1

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14]]])

In [7]:
x1.shape

(1, 3, 5)

In [8]:
x2 = x[:, np.newaxis, :]
x2

array([[[ 0,  1,  2,  3,  4]],

       [[ 5,  6,  7,  8,  9]],

       [[10, 11, 12, 13, 14]]])