In [1]:
import numpy as np

# no.nonzero()

find elements which are not zero, and return the indice of them

### 1-D array

In [2]:
a = np.random.randint(0, 10, size=20)
a

array([0, 6, 0, 9, 1, 5, 3, 7, 7, 6, 2, 7, 2, 7, 8, 3, 8, 3, 3, 2])

In [3]:
np.nonzero(a)

(array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19]),)

In [4]:
a.nonzero()

(array([ 1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
        19]),)

using indice to return the target nonzero elements

In [5]:
a[np.nonzero(a)]

array([6, 9, 1, 5, 3, 7, 7, 6, 2, 7, 2, 7, 8, 3, 8, 3, 3, 2])

### 2-D array

In [6]:
b = np.random.randint(0, 10, size=(4, 5))
b

array([[1, 9, 6, 6, 7],
       [3, 6, 4, 5, 3],
       [3, 0, 7, 4, 5],
       [5, 2, 6, 5, 7]])

return coordinates

In [7]:
np.nonzero(b)

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 2, 3, 4, 0, 1, 2, 3, 4]))

In [8]:
b.nonzero()

(array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 3, 3, 3, 3, 3]),
 array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 2, 3, 4, 0, 1, 2, 3, 4]))

return elements

In [9]:
b[b.nonzero()]

array([1, 9, 6, 6, 7, 3, 6, 4, 5, 3, 3, 7, 4, 5, 5, 2, 6, 5, 7])