In [1]:
import numpy as np

# np.random.rand()

return numbers from 0 to 1 (1 excluded)

In [2]:
np.random.rand()

0.9795481952963215

In [3]:
# generate 2-D numbers
np.random.rand(2, 3)

array([[0.42189844, 0.71326046, 0.44658376],
       [0.17447772, 0.49184999, 0.0567238 ]])

In [9]:
# generate 1-D array with 10 floating number elements ranging from 5 to 10 (10 excluded)
(10 - 5) * np.random.rand(10) + 5

array([6.72228375, 9.82467253, 7.09286356, 5.35273638, 6.63058461,
       6.53282755, 6.66720987, 9.68506339, 8.27552129, 9.71596888])

# np.random.randint()

return integers

In [5]:
# return an integer from 0 to 9
np.random.randint(10)

6

In [6]:
# 2-D arrays full of integers from 0 to 9
np.random.randint(10, size=(2, 3))

array([[7, 5, 6],
       [2, 2, 3]])

In [10]:
# 1-D array with 10 integer elements ranging from 5 to 9
np.random.randint(5, 10, size=10)

array([8, 6, 9, 6, 8, 9, 7, 6, 8, 9])

# np.random.seed()

In [18]:
np.random.seed(seed=21)
np.random.rand()

0.04872488080912729

In [19]:
np.random.seed(seed=21)
np.random.rand()

0.04872488080912729

In [17]:
np.random.seed(10)
a = np.random.rand(20)
a

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])

In [20]:
np.random.seed(23)
b = np.random.rand(20)
b

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009,
       0.00246488, 0.88403218, 0.88494754, 0.30040969, 0.58958187,
       0.97842692, 0.84509382, 0.06507544, 0.29474446, 0.28793444])

In [21]:
np.random.seed(10)
c = np.random.rand(20)
c

array([0.77132064, 0.02075195, 0.63364823, 0.74880388, 0.49850701,
       0.22479665, 0.19806286, 0.76053071, 0.16911084, 0.08833981,
       0.68535982, 0.95339335, 0.00394827, 0.51219226, 0.81262096,
       0.61252607, 0.72175532, 0.29187607, 0.91777412, 0.71457578])

In [22]:
np.random.seed(23)
d = np.random.rand(20)
d

array([0.51729788, 0.9469626 , 0.76545976, 0.28239584, 0.22104536,
       0.68622209, 0.1671392 , 0.39244247, 0.61805235, 0.41193009,
       0.00246488, 0.88403218, 0.88494754, 0.30040969, 0.58958187,
       0.97842692, 0.84509382, 0.06507544, 0.29474446, 0.28793444])

In [24]:
np.all(a == b)

False

In [25]:
np.all(a == c)

True

In [26]:
np.all(b == d)

True

# np.random.choice()

In [28]:
langs = ['Python', 'Ruby', 'Java', 'JavaScript', 'PHP']

In [29]:
np.random.choice(langs, 3)

array(['PHP', 'JavaScript', 'JavaScript'], dtype='<U10')

replace: whether resample duplicate items

In [30]:
np.random.choice(langs, 5, replace=False)

array(['Python', 'Ruby', 'JavaScript', 'Java', 'PHP'], dtype='<U10')

In [31]:
np.random.choice(langs, 5, replace=True)

array(['Java', 'Java', 'PHP', 'JavaScript', 'Python'], dtype='<U10')

p: probability of each item being drawn

In [32]:
np.random.choice(langs, 20, p=[0.8, 0.05, 0.05, 0.05, 0.05])

array(['Java', 'Python', 'Ruby', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Ruby', 'Python', 'Python', 'Python', 'Python', 'Python',
       'Python', 'Python', 'Python', 'Python', 'Python', 'Python'],
      dtype='<U10')

randomly draw integers ranging from 0 to 4

In [33]:
np.random.choice(5, 10)

array([3, 0, 0, 4, 4, 3, 1, 1, 4, 2])

# np.random.shuffle()

in-place shuffle items of an array

In [34]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [35]:
np.random.shuffle(a)
a

array([4, 3, 9, 6, 0, 2, 1, 7, 8, 5])