In [1]:
import numpy as np

# np.tile(array, reps)

reps: times of repetition

In [2]:
a = np.array([0, 1, 2])
a

array([0, 1, 2])

In [3]:
np.tile(a, 2)

array([0, 1, 2, 0, 1, 2])

if reps = (x, y), a 2 dimensional tuple, repetition in two axes

In [4]:
# make repeated 3 axis 0, 2 repeated arrays of elements in the direction of axis 1
np.tile(a, (3, 2))

array([[0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2]])

if reps = (x, y, z), a 3 dimensional tuple, repetition in three axes

In [5]:
np.tile(a, (2, 3, 4))

array([[[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]],

       [[0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2],
        [0, 1, 2, 0, 1, 2, 0, 1, 2, 0, 1, 2]]])