In [1]:
import numpy as np

# np.save()

store into a $.npy$ file

$npy$ file is only allowed to be compatible with Python

In [2]:
a = np.random.randn(1200*1000).reshape(1200, -1)

In [3]:
np.save('myfile', a)

# np.load()

read $.npy$ file

In [5]:
np.load('myfile.npy')

array([[-2.97837533, -1.39094508, -1.51927752, ..., -0.79998605,
         2.01917505,  1.11661509],
       [ 2.35931165, -0.8691628 , -0.41294612, ...,  0.67912497,
        -1.48697276, -1.37330121],
       [ 2.33121319, -0.63509338,  1.1763554 , ...,  0.83132973,
        -0.48365747,  1.31139493],
       ...,
       [ 1.13470508,  0.7002156 , -0.42713117, ...,  0.62864421,
        -1.71645007,  1.05891248],
       [ 0.34021447, -1.08085185, -1.5998542 , ...,  0.3257834 ,
        -1.25325631,  1.17105388],
       [-0.41931631, -0.79290441, -1.30386448, ..., -1.12651777,
        -1.87362956, -1.04969051]])

In [6]:
c = np.random.randn(12 * 20 * 40).reshape(12, 20, 40)
np.save('myfile2', c)

In [7]:
d = np.load('myfile2.npy')
d.shape

(12, 20, 40)

# np.savetxt()

support .txt, .csv, .dat, .gz files

only support 2-D or below dimensional arrays

In [13]:
a = np.random.randn(3, 4)

In [14]:
np.savetxt('sample1.txt', a)

# np.loadtxt()

In [15]:
b = np.loadtxt('sample1.txt')
b

array([[ 1.36198688,  0.68291002, -0.29895788, -1.08767292],
       [-1.99041286,  0.83097358,  0.52509302,  0.60386714],
       [-0.61817274,  1.08880483,  0.35169944, -0.09667124]])

In [16]:
a

array([[ 1.36198688,  0.68291002, -0.29895788, -1.08767292],
       [-1.99041286,  0.83097358,  0.52509302,  0.60386714],
       [-0.61817274,  1.08880483,  0.35169944, -0.09667124]])

In [17]:
np.savetxt('sample.csv', a)

In [18]:
c = np.loadtxt('sample.csv')
c

array([[ 1.36198688,  0.68291002, -0.29895788, -1.08767292],
       [-1.99041286,  0.83097358,  0.52509302,  0.60386714],
       [-0.61817274,  1.08880483,  0.35169944, -0.09667124]])

*delimiter*

In [19]:
np.savetxt('sample2.txt', a, delimiter=',')

In [20]:
try:
    np.loadtxt('sample2.txt')
except ValueError as e:
    print(e)

could not convert string '1.361986882328677595e+00,6.829100210487035749e-01,-2.989578754906453972e-01,-1.087672919738606581e+ to float64 at row 0, column 1.


In [21]:
e = np.loadtxt('sample2.txt', delimiter=',')
e

array([[ 1.36198688,  0.68291002, -0.29895788, -1.08767292],
       [-1.99041286,  0.83097358,  0.52509302,  0.60386714],
       [-0.61817274,  1.08880483,  0.35169944, -0.09667124]])

*fmt* (format)

In [22]:
np.savetxt('sample3.txt', a, fmt='%.2e')

In [23]:
np.savetxt('sample4.txt', a, fmt='%.2f')

*header, footer, comments* 

In [24]:
np.savetxt('sample5.txt', a, fmt='%.3e', header='this is a header', footer='this is a footer')

In [25]:
np.savetxt('sample6.txt', a, fmt='%.3e', header='this is a header', footer='this is a footer', comments='>>>')

*usecols, skiprows*

In [27]:
np.loadtxt('sample4.txt')


array([[ 1.36,  0.68, -0.3 , -1.09],
       [-1.99,  0.83,  0.53,  0.6 ],
       [-0.62,  1.09,  0.35, -0.1 ]])

In [26]:
# fetch 0th and 2nd columns only
np.loadtxt('sample4.txt', usecols=(0, 2))

array([[ 1.36, -0.3 ],
       [-1.99,  0.53],
       [-0.62,  0.35]])

In [30]:
# skip first 1 row
np.loadtxt('sample4.txt', skiprows=1)

array([[-1.99,  0.83,  0.53,  0.6 ],
       [-0.62,  1.09,  0.35, -0.1 ]])

In [31]:
# skip first 2 rows
np.loadtxt('sample4.txt', skiprows=2)

array([-0.62,  1.09,  0.35, -0.1 ])

*dtype, unpack, converts*

In [58]:
np.loadtxt('foo.csv', dtype=[('age', 'i8'), ('gender', 'S10'), ('tall[cm]', 'f8'), ('driving_licence', 'S10')], delimiter=',')

array([(18, b'female', 150., b'No'), (21, b'male', 170., b'Yes'),
       (22, b'female', 160., b'Yes'), (23, b'male', 180., b'Yes'),
       (25, b'female', 150., b'No')],
      dtype=[('age', '<i8'), ('gender', 'S10'), ('tall[cm]', '<f8'), ('driving_licence', 'S10')])

In [59]:
np.loadtxt('foo.csv', dtype=[('age', 'i8'), ('gender', 'S10'), ('tall[cm]', 'f8'), ('driving_licence', 'S10')], unpack=True, delimiter=',')

[array([18, 21, 22, 23, 25]),
 array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10'),
 array([150., 170., 160., 180., 150.]),
 array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')]

In [61]:
age, gender, tall, driving_licence = np.loadtxt('foo.csv', dtype=[('age', 'i8'), ('gender', 'S10'), ('tall[cm]', 'f8'), ('driving_licence', 'S10')], unpack=True, delimiter=',')

In [62]:
age

array([18, 21, 22, 23, 25])

In [63]:
gender

array([b'female', b'male', b'female', b'male', b'female'], dtype='|S10')

In [64]:
tall

array([150., 170., 160., 180., 150.])

In [65]:
driving_licence

array([b'No', b'Yes', b'Yes', b'Yes', b'No'], dtype='|S10')

In [66]:
def driving_licence(string):
    return 1 if string == b'Yes' else 0

def gender(string):
    return 1 if string == b'male' else 0    

In [67]:
np.loadtxt('foo.csv', converters={1: gender, 3: driving_licence}, delimiter=',')

array([[ 18.,   0., 150.,   0.],
       [ 21.,   1., 170.,   1.],
       [ 22.,   0., 160.,   1.],
       [ 23.,   1., 180.,   1.],
       [ 25.,   0., 150.,   0.]])