In [13]:
import time
import numpy as np

# sort(), argsort()

In [2]:
a = np.random.randint(0, 100, size=20)
a

array([98, 43, 66, 28,  2, 50, 36, 24, 67, 97, 25, 54, 65, 74, 97,  3, 38,
       67, 65, 57])

In [3]:
np.sort(a)

array([ 2,  3, 24, 25, 28, 36, 38, 43, 50, 54, 57, 65, 65, 66, 67, 67, 74,
       97, 97, 98])

argsort() returns original indice of sorted elements

In [4]:
a = np.array([1, 3, 2])
np.argsort(a)

array([0, 2, 1])

### sorting 2-D array

In [5]:
b = np.random.randint(0, 100, size=20).reshape(4, 5)
b

array([[88,  1, 30, 96, 63],
       [76, 80, 28, 67, 57],
       [54, 95, 30, 69, 67],
       [80, 71, 53, 94, 16]])

default axis = -1, which means last axis, so start from last axis to sort every 5 elements

In [6]:
np.sort(b)

array([[ 1, 30, 63, 88, 96],
       [28, 57, 67, 76, 80],
       [30, 54, 67, 69, 95],
       [16, 53, 71, 80, 94]])

return indice

In [7]:
np.argsort(b)

array([[1, 2, 4, 0, 3],
       [2, 4, 3, 0, 1],
       [2, 0, 4, 3, 1],
       [4, 2, 1, 0, 3]])

axis = 0, along with axis 0 to sort every 4 elements

In [8]:
np.sort(b, axis=0)

array([[54,  1, 28, 67, 16],
       [76, 71, 30, 69, 57],
       [80, 80, 30, 94, 63],
       [88, 95, 53, 96, 67]])

return indice

In [9]:
np.argsort(b, axis=0)

array([[2, 0, 1, 1, 3],
       [1, 3, 0, 2, 1],
       [3, 1, 2, 3, 0],
       [0, 2, 3, 0, 2]])

### sorting 3-D array

In [10]:
c = np.random.randint(0, 100, size=(2, 4, 5))
c

array([[[71, 89, 92, 28, 26],
        [97, 31, 41,  8, 11],
        [68,  7, 64, 33, 60],
        [10,  8, 23, 31, 77]],

       [[34, 57, 23, 65, 32],
        [88, 81, 79, 82, 99],
        [16, 52,  0, 75, 60],
        [ 2, 31, 71, 24,  9]]])

sorting by axis 0

In [11]:
np.sort(c, axis=0)

array([[[34, 57, 23, 28, 26],
        [88, 31, 41,  8, 11],
        [16,  7,  0, 33, 60],
        [ 2,  8, 23, 24,  9]],

       [[71, 89, 92, 65, 32],
        [97, 81, 79, 82, 99],
        [68, 52, 64, 75, 60],
        [10, 31, 71, 31, 77]]])

return indice

In [12]:
np.argsort(c, axis=0)

array([[[1, 1, 1, 0, 0],
        [1, 0, 0, 0, 0],
        [1, 0, 1, 0, 0],
        [1, 0, 0, 1, 1]],

       [[0, 0, 0, 1, 1],
        [0, 1, 1, 1, 1],
        [0, 1, 0, 1, 1],
        [0, 1, 1, 0, 0]]])

# .sort()

in-place sorting

In [27]:
a = np.random.randint(0, 100, 20)
a

array([60, 96, 16, 23, 85,  7, 94, 99, 49,  8, 89, 49, 66, 37, 84, 65, 41,
       80, 39, 54])

using np.sort(), original a remains the same

In [28]:
np.sort(a)
a

array([60, 96, 16, 23, 85,  7, 94, 99, 49,  8, 89, 49, 66, 37, 84, 65, 41,
       80, 39, 54])

using .sort(), original a will be affected immediately

In [29]:
a.sort()
a

array([ 7,  8, 16, 23, 37, 39, 41, 49, 49, 54, 60, 65, 66, 80, 84, 85, 89,
       94, 96, 99])

### Sorting by order

In [14]:
values = [('Alice', 12, 5.9), ('Spring', 5, 8.9), ('Monkey', 20, 3.5), ('Mia', 15, 6.1)]
dtypes = [('name', 'S10'), ('ID', int), ('score', float)]
a = np.array(values, dtype=dtypes)
a

array([(b'Alice', 12, 5.9), (b'Spring',  5, 8.9), (b'Monkey', 20, 3.5),
       (b'Mia', 15, 6.1)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [15]:
np.sort(a, order='score')

array([(b'Monkey', 20, 3.5), (b'Alice', 12, 5.9), (b'Mia', 15, 6.1),
       (b'Spring',  5, 8.9)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [17]:
np.argsort(a, order='score')

array([2, 0, 3, 1])

In [16]:
np.sort(a, order='ID')

array([(b'Spring',  5, 8.9), (b'Alice', 12, 5.9), (b'Mia', 15, 6.1),
       (b'Monkey', 20, 3.5)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

In [18]:
np.sort(a, order=['score', 'ID'])

array([(b'Monkey', 20, 3.5), (b'Alice', 12, 5.9), (b'Mia', 15, 6.1),
       (b'Spring',  5, 8.9)],
      dtype=[('name', 'S10'), ('ID', '<i8'), ('score', '<f8')])

Compare sorting algorithms

In [21]:

def compare_sorting_methods(arr: np.ndarray):
    start_time = time.time()
    np.sort(arr, kind='quicksort')  # default
    print(f'Quicksort: {time.time() - start_time} sec')
    
    start_time = time.time()
    np.sort(arr, kind='mergesort')
    print(f'Mergesort: {time.time() - start_time} sec')
    
    start_time = time.time()
    np.sort(arr, kind='heapsort')
    print(f'Heapsort: {time.time() - start_time} sec')

In [22]:
arr = np.random.randn(100)

compare_sorting_methods(arr)

Quicksort: 0.00036716461181640625 sec
Mergesort: 1.4066696166992188e-05 sec
Heapsort: 5.9604644775390625e-06 sec


In [23]:
arr = np.random.randn(1000)

compare_sorting_methods(arr)

Quicksort: 0.0010769367218017578 sec
Mergesort: 0.0008060932159423828 sec
Heapsort: 8.893013000488281e-05 sec


In [24]:
arr = np.random.randn(10_000)

compare_sorting_methods(arr)

Quicksort: 0.00016808509826660156 sec
Mergesort: 0.000982046127319336 sec
Heapsort: 0.0008900165557861328 sec


In [26]:
arr = np.random.randn(100_000)
compare_sorting_methods(arr)

Quicksort: 0.0014967918395996094 sec
Mergesort: 0.009937286376953125 sec
Heapsort: 0.013569831848144531 sec
