In [1]:
import numpy as np

# np.where(condition, x, y)

In [2]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

Return indices of satisfied elements

In [3]:
np.where(a < 10)

(array([6, 7, 8, 9]),)

Retrieve elements by indexing

In [4]:
a[np.where(a < 10)]

array([8, 6, 4, 2])

In [5]:
a = np.arange(12).reshape(3, 4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

find the locations of all even numbers

return the coordinates of satisfied elements

In [6]:
np.where(a % 2 == 0)

(array([0, 0, 1, 1, 2, 2]), array([0, 2, 0, 2, 0, 2]))

Retrieve elements

In [7]:
a[np.where(a % 2 == 0)]

array([ 0,  2,  4,  6,  8, 10])

conditional assignment

In [8]:
np.where(a % 2 == 0, 'even', 'odd')

array([['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd'],
       ['even', 'odd', 'even', 'odd']], dtype='<U4')

In [9]:
try:
    np.where(a % 2 == 0, 'even')
except ValueError as e:
    print(e)

either both or neither of x and y should be given


In [10]:
b = np.reshape(a, (3, 4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [11]:
c = b ** 2
c

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

Any of elements in b meets the condition, then being kept as element in b

Any of elements in b doesn't satisfy demand, then being replaced by the corresponding element in c

In [12]:
np.where(b % 2 == 0, b, c)

array([[  0,   1,   2,   9],
       [  4,  25,   6,  49],
       [  8,  81,  10, 121]])